test(e2e): enhance e2e tests, including predicated variants
evolv-ai/asset-manager pull request #172
Opened 2021-01-29 01:56 UTC by mattstrom

[RKT-7917]

2021-01-29 01:58 UTC, mattstrom commented
Waiting on `javascript-sdk` PR to get the associated semver.

2021-02-02 19:49 UTC, FrazerBayley requested changes

2021-02-02 19:49 UTC, FrazerBayley commented on e2e/tests/targeting/predicated-variants/multiple-experiments.test.ts
> +	const activeKeys = await getActiveKeys();
As well as verifying the activeKeys can you verify the active variants in the context as well?

2021-02-03 01:46 UTC, FrazerBayley approved these changes

2021-02-03 01:49 UTC, merged