feat: rework asset-manager for better timing support
evolv-ai/asset-manager pull request #191
Opened 2021-03-27 02:13 UTC by mattstrom

[RKT-8830]

2021-03-27 16:54 UTC, robertsevernsentient reviewed
hotfix-v1.8

2021-03-27 16:54 UTC, robertsevernsentient commented on src/runner.js
> +        if (!this.confirmed) {
I think this should be removed -- if it's left in then on an SPA we won't try to confirm a new context if the page isn't reload

2021-03-27 16:54 UTC, robertsevernsentient commented on src/tests/runner.test.js
> +import * as assert from 'assert';
Plenty more cases I want us to unit test here -- but enough to get deployed for manual testing

2021-03-27 16:56 UTC, robertsevernsentient requested changes
We need to understand why the index.js tests are failing before we can merge and deploy

2021-03-28 00:23 UTC, mattstrom commented
> We need to understand why the index.js tests are failing before we can merge and deploy

@robertsevernsentient: I've corrected nearly all of the failing tests, except for this one which I haven't been able to discern the intent of yet. The test fails because `invokedJavascript.length` equals 6 instead of 7. There's a nearly identical block just above it.

Any thoughts? Maybe there's supposed to be a redundant invocation:
https://github.com/evolv-ai/asset-manager/blob/1c3ff2b7e6e157137dd8a6f034c37f0e5b4447cb/src/tests/index.test.js#L539-L546

2021-03-28 01:15 UTC, robertsevernsentient commented
> > We need to understand why the index.js tests are failing before we can merge and deploy
> 
> @robertsevernsentient: I've corrected nearly all of the failing tests, except for this one which I haven't been able to discern the intent of yet. The test fails because `invokedJavascript.length` equals 6 instead of 7. There's a nearly identical block just above it.
> 
> Any thoughts? Maybe there's supposed to be a redundant invocation:
> https://github.com/evolv-ai/asset-manager/blob/1c3ff2b7e6e157137dd8a6f034c37f0e5b4447cb/src/tests/index.test.js#L539-L546

Looking into it now @mattstrom -- basic issue is that 'evolv_web_page1' wasn't marked resolved -- so didn't get marked as runnable again when the key was removed

2021-03-28 01:57 UTC, robertsevernsentient commented
> > > We need to understand why the index.js tests are failing before we can merge and deploy
> > 
> > 
> > @robertsevernsentient: I've corrected nearly all of the failing tests, except for this one which I haven't been able to discern the intent of yet. The test fails because `invokedJavascript.length` equals 6 instead of 7. There's a nearly identical block just above it.
> > Any thoughts? Maybe there's supposed to be a redundant invocation:
> > https://github.com/evolv-ai/asset-manager/blob/1c3ff2b7e6e157137dd8a6f034c37f0e5b4447cb/src/tests/index.test.js#L539-L546
> 
> Looking into it now @mattstrom -- basic issue is that 'evolv_web_page1' wasn't marked resolved -- so didn't get marked as runnable again when the key was removed

I had to change unschedule to successfully unschedule resolved functions too

2021-03-28 16:50 UTC, robertsevernsentient approved these changes

2021-03-28 16:51 UTC, merged

2021-03-28 17:03 UTC, robertsevernsentient commented
hotfix-v1.8